set -g status-style "bg=#3c3836,fg=#b8bb26"
set -g status-right "GPU: #{gpu_percentage} CPU: #{cpu_percentage} MEM: #{ram_percentage}"
setw -g mouse on
run-shell ~/.config/tmux/tmux-cpu/cpu.tmux
unbind -n MouseDown2Pane
unbind -n MouseUp2Pane
